---
# handlers file for elasticsearch
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart elasticsearch
  systemd: name=kibana state=restarted enabled=yes
