---

- name: ISM Plugin Install | Download Opendistro Elasticsearch ism plugin {{ opendistro_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_ism_download_url }}opendistro_index_management-{{ opendistro_plugin_version }}.zip"
    dest: "{{ es_home }}/opendistro_index_management-{{ opendistro_plugin_version }}.zip"
  register: download

- name: ISM Plugin Install | Install the Opendistro ism plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro_index_management-{{ opendistro_plugin_version }}.zip"
  when: download.changed
  notify: restart elasticsearch
